var name = prompt ("What is your name?");
alert("Hello, " +name);
var a;
a = 5000;
alert (a);
var phrase = "This is a simple phrase.";
alert (phrase.length);
var aa =100;
var bb = 50;
var result = var aa - var bb;
